### ISSUE TITLE
🥇 ElixirのGH Actionsを追加する

### ISSUE THREAD

**Issue by HidemaruOwO** [HidemaruOwO/Awesome-HelloWorld#4]
Elixirのチェックのworkflowを書く

**Comment by HidemaruOwO** [comment]
公式ドキュメントのまま書いても失敗するので、一旦諦め

https://github.com/erlef/setup-beam

```yml
# create this in .github/workflows/ci.yml
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['20.3', '21.3', '22.2']
        elixir: ['1.8.2', '1.9.4']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
  ```
