### ISSUE TITLE
🥇  Javascript 1のworkflowを追加する

### ISSUE THREAD

**Issue by HidemaruOwO** [HidemaruOwO/Awesome-HelloWorld#9]

**Comment by HidemaruOwO** [comment]
@s1204IT これはTypeScriptと並行して対応できそうなので、自分が追加しても良いですか？

**Comment by HidemaruOwO** [comment]
JSのCI

```yml
name: JavaScript 1

on:
  push:
    paths:
      - '.github/worlflows/js-1.yml'
      - 'javascript/hello_world_1/**'
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Hello World!!
        run: deno run ./javascript/hello_world_1/main.js
```
